spring:
  application:
    name: test-spring
  datasource:
    url: jdbc:h2:tcp://localhost/~/testApi
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update    #update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug  #??? sql? ??? ??? ????.
    org.hibernate.orm.jdbc.bind: trace  #??? ?? 3.x, hibernate6
#
#server:
#  port: 7978